# Gitleaks configuration for WorkTrack
# This file excludes false positives from generated files and common patterns

version = "8.24.3"

# Global settings
[global]
    # Scan only the latest commit (faster for CI)
    scan-commits = true
    scan-staged = false
    scan-unstaged = false
    
    # Redact secrets in output
    redact = true
    
    # Exit code when leaks are found
    exit-code = 2

# Allowlist patterns for generated files and false positives
[allowlist]
    # Exclude specific files
    files = [
        "android/app/google-services.json",
        "ios/Podfile.lock", 
        "package-lock.json",
        "yarn.lock",
        "android/gradle/wrapper/gradle-wrapper.properties"
    ]
    
    # Exclude directories
    paths = [
        "android/app/build/",
        "ios/build/",
        "node_modules/",
        "coverage/"
    ]
    
    # Exclude specific regex patterns
    regexes = [
        "com\\.reactnative\\.[a-zA-Z0-9.-]+",  # React Native bundle IDs
        "WorkTrack"  # App name
    ]

# Use default rules
[default]
    use-default = true
