module.exports = {
	preset: 'react-native',
	testMatch: ['**/__tests__/**/*.test.(ts|tsx)'],
	transformIgnorePatterns: [
		'node_modules/(?!(react-native|@react-native|@nozbe|@react-native-firebase|@react-navigation|react-native-gesture-handler|react-redux)/)',
	],
	setupFiles: ['./jest.setup.js'],
	setupFilesAfterEnv: ['react-native-gesture-handler/jestSetup'],
	moduleNameMapper: {
		'^react-native$': 'react-native',
		'^@env$': './__mocks__/@env.js',
	},
	clearMocks: true,
	resetMocks: true,
	restoreMocks: true,
	maxWorkers: 1,
	collectCoverageFrom: [
		'src/{repositories,services,use-cases,mappers,logging,utils,db}/**/*.{ts,tsx}',
		'!src/**/index.ts',
		'!src/**/index.tsx',
		'!src/**/*.d.ts',
		'!src/db/**/*schema.ts',
		'!src/db/**/*model.ts',
		'!src/db/watermelon/worktrack/load.ts',
		'!src/utils/appDataManager.ts',
		'!src/utils/shareValidation.ts',
	],
	coveragePathIgnorePatterns: [
		'/node_modules/',
		'<rootDir>/src/components/',
		'<rootDir>/src/screens/',
		'<rootDir>/src/navigation/',
		'<rootDir>/src/hooks/',
		'<rootDir>/src/themes/',
		'<rootDir>/src/store/',
		'<rootDir>/src/types/',
		'<rootDir>/src/constants/',
		'<rootDir>/src/assets/',
	],
	coverageDirectory: 'coverage',
	coverageReporters: ['lcov', 'text', 'text-summary'],
	coverageThreshold: {
		global: {
			branches: 95,
			functions: 95,
			lines: 95,
			statements: 95,
		},
	},
};
