module.exports = {
	preset: 'react-native',
	testMatch: ['**/__tests__/**/*.test.(ts|tsx)'],
	transformIgnorePatterns: [
		'node_modules/(?!(react-native|@react-native|@nozbe|@react-native-firebase|@react-navigation|react-native-gesture-handler|react-redux|immer)/)',
	],
	setupFiles: ['./jest.setup.js'],
	// setupFilesAfterEnv: ['react-native-gesture-handler/jestSetup'],
	moduleNameMapper: {
		'^react-native$': 'react-native',
		'^@env$': './__mocks__/@env.js',
	},
	clearMocks: true,
	resetMocks: true,
	restoreMocks: true,
	maxWorkers: 1,
	testTimeout: 10000,
	collectCoverageFrom: [
		'src/{repositories,services,use-cases,mappers,logging,utils,db,components,screens,hooks,navigation,store,themes,constants,types}/**/*.{ts,tsx}',
		'!src/**/index.ts',
		'!src/**/index.tsx',
		'!src/**/*.d.ts',
		'!src/db/**/*schema.ts',
		'!src/db/**/*model.ts',
		'!src/db/watermelon/worktrack/load.ts',
		'!src/utils/appDataManager.ts',
		'!src/utils/shareValidation.ts',
		'!src/screens/Authenticated/HomeScreen.tsx',
		'!src/screens/Authenticated/ProfileScreen.tsx',
		'!src/screens/WelcomeScreen.tsx',
		'!src/screens/LoadingScreen.tsx',
		'!src/components/common/Dialog.tsx',
		'!src/components/sync/SyncErrorBanner.tsx',
		'!src/components/sync/SyncStatusIndicator.tsx',
		'!src/components/worktrack/WorkTrackSwitcher.tsx',
		'!src/components/worktrack/DayMarkingBottomSheet.tsx',
		'!src/components/Profile/ShareListItem.tsx',
		'!src/components/Profile/SharedWithMeListItem.tsx',
		'!src/components/Calendar/CustomCalendar.tsx',
		'!src/components/ui/GlobalToast.tsx',
		'!src/hooks/useWorkTrackManager.ts',
		'!src/hooks/useResponsive.ts',
		'!src/hooks/useSharedWorkTracks.ts',
		'!src/navigation/MainNavigator.tsx',
		'!src/store/reducers/workTrackSlice.ts',
	],
	coveragePathIgnorePatterns: ['/node_modules/', '<rootDir>/src/assets/'],
	coverageDirectory: 'coverage',
	coverageReporters: ['lcov', 'text', 'text-summary'],
	coverageThreshold: {
		global: {
			branches: 95,
			functions: 95,
			lines: 95,
			statements: 95,
		},
	},
};
